### ISSUE TITLE
How to list keys?

### ISSUE THREAD

**Issue by yoshuawuyts** [mafintosh/hyperdb#10]
I was wondering how to list the keys for a directory. I remember that pre the `1.0.0-rc` there was an iterator method, but it seems to have been removed.

The use case for this is time series data; being able to iterate over keys is probably a requirement for most applications of this kind haha.

**Comment by mafintosh** [comment]
See the 1.1 goals here, https://github.com/mafintosh/hyperdb/pull/1#issue-248276790

**Comment by yoshuawuyts** [comment]
Awesome, missed that comment. Thanks for answering!

**Comment by mafintosh** [comment]
Ya kinda hard to find in a closed pr hehe
