### ISSUE TITLE
Iterator should support `reverse` option

### ISSUE THREAD

**Issue by andrewosh** [mafintosh/hyperdb#107]
I'm working through some issues with using hyperdb as a leveldown backend (https://github.com/andrewosh/hyperdbdown). #105 + #97 + #104 should cover most of the remaining features/issues, but an efficient approach to reverse iteration would also be expected.

Any thoughts on how to tackle this? I'm scratching my head a bit -- as it stands, the DFS trie search doesn't seem very amenable to reverse iteration, but maybe there's "one simple trick" I'm not seeing.

**Comment by mafintosh** [comment]
@andrewosh if you just flip the current sort order wouldn't it be reverse? :thinking:

**Comment by e-e-e** [comment]
@andrewosh I also shared the same intuition as you. It's great that its so simple.

**Comment by mafintosh** [comment]
you fixed this in latest! :)
