### ISSUE TITLE
Disappearing writer, perhaps from corrupt vector clock

### ISSUE THREAD

**Issue by xloem** [mafintosh/hyperdb#117]
I have a database where my authorized writer has somehow disappeared.  It may be related to a couple mishaps with incorrectly specifying the vector clock, I'm not sure.  (I've been manually passing it so that I can include a hash of the matching heads in the data).

I've uploaded the corrupt hyperdb to https://sharedthings-xloem.hashbase.io/hyperstream-test-db-corrupt/ .  A feed is no longer generated for `74477aa8444f9da4b41be53d131db308a3bb329725eef4b81a6e2f5fe0fa62a5` but this key has been authorized.

It's concerning to me that a bug like this can make a contributor disappear.  Perhaps whatever invalid message caused it should be detected and rejected somewhere.

**Comment by mafintosh** [comment]
Which version of hyperdb did you use to write this db?

**Comment by mafintosh** [comment]
Ah you're prob hitting some of the corruption bugs @jimpick has been fixing in master the last days. I'll get a new release out later today with the fix. Also includes some runtime assertions to detect it if it were to happen again.

**Comment by xloem** [comment]
oh, great !  I guess I should really be using git master all the time if I'm going to be posting issues and such. sorry !
