### ISSUE TITLE
batch API

### ISSUE THREAD

**Issue by noffle** [mafintosh/hyperdb#13]
Wanted: an API method for batch document insertions. Something not unlike [`hyperkv#batch`](https://github.com/substack/hyperkv#kvbatchrows-opts-cb), but maybe sans the `delete` operation and the ability to set `links` to parents, since those seem more like concepts to layered *above* hyperdb than direct concerns of its.

**Comment by e-e-e** [comment]
@mafintosh this is now done, no?

**Comment by noffle** [comment]
@e-e-e oh snap, so it is! Thanks for noticing.
