### ISSUE TITLE
Batch isn't atomic

### ISSUE THREAD

**Issue by andrewosh** [mafintosh/hyperdb#130]
To my understanding, `db.batch` currently does independent puts for each element in the input list. If one of these writes were to fail, the previous writes in the batch would still be accessible. 

One way to fix this would be to add an optional `batch` identifier to Entry that's a pointer to a batch completion record (inserted when the batch is successful). During `get`, if an Entry is part of a batch, but its batch pointer points to a nonexistent entry, then the record should also be treated as nonexistent.

The overhead here is that each `get` on batched entries would require a second lookup, and failed batches can fill the DB with unreachable entries that consume space (would need to be able to `clear` these).

**Comment by mafintosh** [comment]
Actually it should be atomic already but could def use more test covs (I'm not sure we even test the atomicity atm, so there could def be bugs)

The way it currently works is that all puts are done in series in the batch, *but* they are not commited to the feed but instead to a simple array, https://github.com/mafintosh/hyperdb/blob/master/index.js#L95-L96.

Once all nodes in the batch have been added there they are all passed to hypercore's feed.append which only signs the last node making in the batch making it atomic (you need the sig the verify any of the them).

Makes sense?

**Comment by andrewosh** [comment]
Ah, shouldn't have been so confident :) 

The line that I missed was in the [Writer's append](https://github.com/mafintosh/hyperdb/blob/48c76a1ed676961f7792dadab8bd561db8586878/index.js#L746) actually. Didn't realize that the `put` calls wouldn't immediately do an insertion, so I thought there could be an inconsistent state.
