### ISSUE TITLE
Reading data from source db using public/discovery key?

### ISSUE THREAD

**Issue by jmul-dev** [mafintosh/hyperdb#139]
I'm new to hyperdb and I'm sorry if this is a stupid question.

First, I create a db using the following commands:
```
const hyperdb = require("hyperdb");
const db = hyperdb("./test.db", "SOMEKEY", { valueEncoding: "json" });

db.on("ready", function() {
   console.log(db.key.toString("hex");
   console.log(db.discoveryKey.toString("hex");
});

db.put('/hello', 'world', function (err) {
  if (err) throw err
  db.get('/hello', function (err, nodes) {
    if (err) throw err
    console.log('/hello --> ' + nodes[0].value)
  })
})
```

From there, I know my source db's public key and discovery key. 

My question is, is it possible to create a new instance of hyperdb and read data from the source?

I tried doing
```
const ram = require("random-access-memory");
const hyperdb = require("hyperdb");
const db2 = hyperdb(function ('SOURCE_DB_PUBLIC_KEY') {
   return ram();
});

db2.on("ready", function() {
  db2.list("/", function(err, nodes) {
     console.log(nodes);
  });
});
```
But it doesn't seem to return anything. Am I missing something?

**Comment by e-e-e** [comment]
The step that you are missing is a discovery swarm or some other form of replicating the dbs.
For HyperReadings we use [hyperdiscovery](https://github.com/karissa/hyperdiscovery) - for example 
imported here https://github.com/e-e-e/hyper-readings-manager/blob/master/src/manager.js#L5 and then called here
https://github.com/sdockray/hyperreadings/blob/master/lib/hyperreadings.js#L46-L57.
Once both db's are connected to a swarm you will be able to find the db by its pubic key.

**Comment by jmul-dev** [comment]
Ah thanks @e-e-e I'll check it out!

**Comment by e-e-e** [comment]
Also if this is helpful, I have been hacking on getting stats working too - 
+ network speed - https://github.com/e-e-e/hyper-readings-manager/blob/master/src/hyperdb-network-speed.js (based on @joehand's implementation in dat-node)
+ storage - https://github.com/e-e-e/hyper-readings-manager/blob/master/src/hyperdb-storage-stats.js

**Comment by aral** [comment]
For anyone else stumbling on this thread: see https://github.com/cblgh/hyperdb-examples for a working example.

**Comment by jmul-dev** [comment]
Thanks @aral ! will check it out
