### ISSUE TITLE
84 failing tests with hypercore >= v6.18.2

### ISSUE THREAD

**Issue by G-Ray** [mafintosh/hyperdb#151]
Tests do not pass with hypercore >= v6.18.2 due to this commit: https://github.com/mafintosh/hypercore/commit/e7d82f1dd0785a43d9c4f15dab93e3e175b527f3

**Comment by mafintosh** [comment]
Thanks for reporting this. This was actually a hypercore bug that is fixed in latest (https://github.com/mafintosh/hypercore/commit/3bc45ecbeab0f3dd78c5d4bb810a5629bcb00e37)

If you re-install deps, all tests should pass.
