### ISSUE TITLE
createHistoryStream

### ISSUE THREAD

**Issue by noffle** [mafintosh/hyperdb#16]
It would be great if there was a way to get a stream of nodes of a key's history, starting at HEAD and moving backwards in time.

**Comment by noffle** [comment]
I'm thinking something like https://github.com/substack/hyperkv#var-stream--kvcreatehistorystreamkey-opts

**Comment by e-e-e** [comment]
@noffle I think this is done right? Albeit without back pressure.

**Comment by noffle** [comment]
Oh hey, you're right! Thanks @e-e-e.
