### ISSUE TITLE
iterate all keys

### ISSUE THREAD

**Issue by maxogden** [mafintosh/hyperdb#17]
i have a couple use cases where i need to basically .createReadStream() all keys in the entire hyperdb, e.g. for exporting the whole thing to a csv

**Comment by noffle** [comment]
If you just need current keys and not historic values, you could do `db.createDiffStream('/')` and filter out the `delete` entries.

**Comment by noffle** [comment]
If you need all historic values (basically, the whole DAG) you'll be able to use a [history stream](https://github.com/mafintosh/hyperdb/issues/16). (soon)

**Comment by jayrbolton** [comment]
what do you think about having a method like `db.find("*")` (or eg. `db.find("/*/prefix/*/wat/*")`)that accepts splats? It would return a readable stream that gets data for each found node.

if yall think this is a good idea, i would enjoy figuring out the trie traversal necessary to make this work. I was wanting something like this recently myself.

**Comment by noffle** [comment]
@jayrbolton  I think it'd be a cool API to have. :+1:

**Comment by mafintosh** [comment]
in master

**Comment by mafintosh** [comment]
@jayrbolton the iterators in master are sorted by hash which means you can actually efficiently implement the `/*/prefix/*/...` pattern. let me know if you need some pointers and i'll be happy to help
