### ISSUE TITLE
Cannot pipe stream from createDiffStream.

### ISSUE THREAD

**Issue by e-e-e** [mafintosh/hyperdb#28]
When I try and pipe the stream returned from db.createDiffStream() I get this error: 
> Uncaught TypeError: Invalid data, chunk must be a string or buffer, not object

Here is an example to replicate.
```js
var db = hyperdb(ramStore)
db.put('/hello', 'world', () => {
      var stream = db.createDiffStream('/')
      stream.pipe(process.stdout)
      stream.on('end', done)
})
```

This throws for any destination stream - including PassThrough.

I am using node v6.11.2

Will these PR’s will fix this issue - https://github.com/mafintosh/hyperdb/pull/24, https://github.com/mafintosh/hyperdb/pull/23?

**Comment by noffle** [comment]
Hey @e-e-e. `db.createDiffStream()` returns an *object* stream, not a buffer stream (like `process.stdout`). You'll need to pipe it into a stream that uses a [object mode](https://nodejs.org/api/stream.html#stream_object_mode).

**Comment by e-e-e** [comment]
@noffle thanks so much for clarifying. I didn't know about object mode - so also super nice to refine my understanding of nodes stream api.
