### ISSUE TITLE
.createHistoryStream exit when running with the live: true option

### ISSUE THREAD

**Issue by Mayeu** [mafintosh/hyperdb#56]
Hello :wave: 

I am playing with hyperdb trying to wrap my head around how it works, and it seems that I am facing a bug with the `.createHistoryStream({ live: true })` which stop and exit without error.

Here is the minimal example:
```javascript
"use strict";
var hyperdb = require("hyperdb");

var db = hyperdb("./historyStream.db", { valueEncoding: "utf-8" });

function watchFeed() {
  var stream = db.createHistoryStream({ live: true });
  stream.on("data", console.log);
  stream.on("end", console.log);
  stream.on("finish", console.log);
  stream.on("error", console.log);
}

db.on("ready", () => {
  db.put("/key1", "value1", err => {
    if (err) throw err;
  });

  watchFeed();
});
```

Running this, I expect to see the output of `/key1` and then the script to hang until new value are added to the DB, but the script just exist when the stream reach the end. Here is the output:
```
🚀  λ node historyStream.db1.js
{ key: '/key1',
  value: 'value1',
  clock: [ 0 ],
  trie: [],
  feeds: 
   [ { key: <Buffer 8e 8d 5a 38 ca 6c 29 00 56 52 87 60 9d 7f 2e 59 37 8d 97 ff ba f3 12 05 9a 5f 4e 53 85 03 79 95>,
       owner: true } ],
  feedSeq: 0,
  feed: 0,
  seq: 0,
  path: 
   [ 0,
     2,
     0,
     1,
     1,
     1,
     1,
     1,
     3,
     0,
     3,
     1,
     2,
     1,
     0,
     2,
     3,
     2,
     2,
     0,
     1,
     3,
     0,
     1,
     3,
     0,
     1,
     0,
     1,
     3,
     0,
     2,
     4 ] }
 
🚀 λ
```

Did I do something wrong, or does it looks like a bug?

Thank you for any help.

**Comment by Mayeu** [comment]
Small additional info, here is my node version:
```
🚀  λ node -v && npm -v
v8.9.4
5.6.0
```
And you can find the `package-lock.json` in [this gist](https://gist.github.com/Mayeu/f9638ff5afa359f90d8ae24ea4b3383f#file-package-lock-json).

**Comment by noffle** [comment]
Ha, I thought about this a bunch, but I *think* this is OK behaviour.

If this was your actual progam, it would hang forever. There's no new data source that would ever add new data to the live history stream, right? Imagine you had a source for new data though, like a network socket. The presence of that open socket would keep the node process alive. In fact, I *think* any external data source that could potentially make hyperdb writes would be something that kept the node process alive. Does that make sense?

**Comment by Mayeu** [comment]
Hey @noffle, I understand your point, and it make sense that the process halt in the context of only one data source.

In this context, that would mean that this should block (since I am showing via `db1` which is also listenning to another feed): 
```javascript
"use strict";
var util = require("util");
var hyperdb = require("hyperdb");

var db1 = hyperdb("./historyStream.db1", { valueEncoding: "utf-8" });
var db2;

function watchFeed() {
  var stream = db1.createHistoryStream({ live: true });
  stream.on("data", console.log);
  stream.on("end", console.log);
  stream.on("finish", console.log);
  stream.on("error", console.log);
}

db1.on("ready", () => {
  db2 = hyperdb("./historyStream.db2", db1.key, { valueEncoding: "utf-8" });
  db2.on("ready", () => {
    db1.authorize(db2.local.key, () => {
      var stream = db1.replicate({ live: true });
      stream
        .pipe(db2.replicate({ live: true }))
        .pipe(stream)
        .on("end", console.log);

      db1.put("/key1", "value1", err => {
        if (err) throw err;
        db2.put("/key2", "value2", console.log);
      });

      watchFeed();
    });
  });
});
```

To clarify my goals with this: what I would like to do is something that I can keep running while developing and testing tools around hyperdb to see what is happening. Maybe that already exists, or maybe I am not doing the right thing at all :)

**Comment by Mayeu** [comment]
Ha OK I see. So **I should be the one blocking the Node process** with something else. So joining a dat swarm and keeping the process listening to it should do it right?

**Comment by noffle** [comment]
Right!

**Comment by Mayeu** [comment]
:ok_hand:

Then I'm clossing this, and will see how I can do that :D 

Thank you for the help!
