### ISSUE TITLE
Nitty Gritty Questions

### ISSUE THREAD

**Issue by bnewbold** [mafintosh/hyperdb#57]
While writing up a DEP for hyperdb, a couple corner cases have come up needing clarification:

1. For keys, a leading slash is optional: in applications, `get('hello')` is the same as `get('/hello')`. Does the library normalize this internally? Eg, always stores with a leading slash in the actual protobuf?
2. Is it possible to have a "key" that is also a "prefix"? Eg, have the keys `/a/b/c` and `/a/b` at the same time.
3. When using prefixes, I assume that only "complete" path segments are used. Eg, if key `/abc/def` exists, then `list('/abc/')` will return the key, but `list('/abc/d')` will not.
4. Related to 3, should a trailing slash be required for prefixes? Eg, `list('/a/b')` vs. `list('/a/b/')`.

**Comment by noffle** [comment]
I'll take a shot at these.

> 1. For keys, a leading slash is optional: in applications,
> `get('hello')` is the same as `get('/hello')`. Does the library
> normalize this internally? Eg, always stores with a leading slash in
> the actual protobuf?

Yes! Check out the parsing code in `lib/hash.js`:

```js
function split (key) {
  var list = key.split('/')
  if (list[0] === '') list.shift()
  if (list[list.length - 1] === '') list.pop()
  return list
}
```

Leading and trailing slashes get trimmed.

> 2. Is it possible to have a "key" that is also a "prefix"? Eg, have
> the keys `/a/b/c` and `/a/b` at the same time.

Yes.

> 3. When using prefixes, I assume that only "complete" path segments
> are used. Eg, if key `/abc/def` exists, then `list('/abc/')` will
> return the key, but `list('/abc/d')` will not.

What is "list" here? But yes, prefixes start & stop on the slashes.

> 4. Related to 3, should a trailing slash be required for prefixes? Eg, `list('/a/b')` vs. `list('/a/b/')`.

As per (1), the trailing slash doesn't matter.

**Comment by bnewbold** [comment]
Thanks! My current DEP progress (including these answers) is here: https://github.com/datprotocol/DEPs/pull/3

A couple more specific questions:

- It looks like there isn't an actual protobuf schema under the `next` branch of hyperdb, it's still at an abstract state. is that correct?
- I'm assuming that deletions will work similar to how they did with the old hyperdrive system. Without going back to review the details of how that worked, I think you basically write a Node with an undefined value (and "undefined" is different from "zero-byte length"; it should be possible to write the empty (byte-)string). What i'm unsure about is whether these deletion tombstones stick around in the trie, or if new insertions specifically do not include references to deletion-only Nodes in their trie.
- the hash function (`crypto_shorthash`) requires a key. the current implementation allocates a key; I assume from context that javascript/node is zero-ing this buffer, and that we intent to always use a zero'd key for all hashing operations
- are we ignoring the potential for hash collisions? using [this table][table] (instead of calculating myself), it looks like with 60 million keys (at the same path prefix), there is a 1-in-10k chance of a collision. That's a lot of keys, but maybe not totally out of scope, and a non-trivial probability.

[table]: http://preshing.com/images/small-probabilities.png

And a non-question note:
- it feels like treating the shorthash output as a uint64 and doing the bit manipulation on that would be faster than doing things byte-by-byte... it would also likely change the order of the `path` elements. This might raise byte-order ambiguity depending on how implementations did their bit arithmetic though?

**Comment by e-e-e** [comment]
@bnewbold - to add to your questions.  
If you create a readStream or list from a given key is it expect that, given the key has a value, it is also returned or just the nested keys. See this PR for test which illustrates what I mean: https://github.com/mafintosh/hyperdb/pull/61
At the moment it fails on next.

**Comment by mafintosh** [comment]
@bnewbold 

* we can handle hash collisions (reminder to myself to add a test for that).
* on the using a uint64. that be perfect if js had 64bit ints :D
* deletes for now stick around in the trie (this is mostly so can ship it, but there are plans in motion for making that part better)
* protobuf added

next is in a mergeable state now. i'll be adding a few more tests tonight and then hitting the merge button

**Comment by bnewbold** [comment]
My questions were answered here, so closing. @e-e-e, if you want your questions tracked i'd open a new issue.

**Comment by e-e-e** [comment]
@bnewbold - no problem. My question was answered on #dat irc - and resolved in this PR https://github.com/mafintosh/hyperdb/pull/71. We now have the option to specify whether an iterator is inclusive or exclusive of the searched prefix. ✨
