### ISSUE TITLE
query authorized keys

### ISSUE THREAD

**Issue by noffle** [mafintosh/hyperdb#63]
`hyperdb#authorize` makes it possible to authorize new keys, but there's no API for querying this information. The only way I can think of right now is running a `hyperdb#createHistoryStream` over all historic data (and perhaps indexing that locally).

**Comment by noffle** [comment]
If I correctly grok how authorization works, this should just be a matter of iterating over `_writers` and checking for that key.

**Comment by mafintosh** [comment]
db.feeds contain all authorized keys. there is an api called .authorized(key) -> bool as well. we prob need docs for both

**Comment by noffle** [comment]
+1 for docs!

**Comment by derhuerst** [comment]
AFAICT this is done. `authorize` and `authorized` are documented in the readme.
