### ISSUE TITLE
proposal: createKeyStream

### ISSUE THREAD

**Issue by m-onz** [mafintosh/hyperdb#67]
It would be really handy to be able to see all the keys that have been set with something like...

```
var r = db.createKeyStream()
r.pipe(process.stdout)
```

or 

```
db.getKeys('/prefix', function (e, keys) {
    if (!e) console.log('these keys have been set ', keys);
})
```

BTW createHistoryStream seems to be missing from the latest version. I guess the library API is changing but it would be nice to be able to build an "explorer" / visualization tool that lets you see all the data inside a HyperDB

I am planning to build an electron app that can do this once the library API becomes static.

**Comment by noffle** [comment]
Is [createReadStream](https://github.com/mafintosh/hyperdb#var-stream--dbcreatereadstreamprefix-options) is what you're after?

**Comment by mafintosh** [comment]
Yea, read stream should do the trick. We could add a .createValueStream + .createKeyStream that are simple through streams on top that uses map to map the nodes for ease of use

```js
HyperDB.prototype.createKeyStream = function () {
  return db.createReadStream({map: node => node.key, reduce: (a, b) => a})
}
```

**Comment by m-onz** [comment]
Derp! Quite possibly yes. I will close this issue tommorow once I've
investigated a bit more.

**Comment by m-onz** [comment]
Perfect! Thanks 👍
