### ISSUE TITLE
key not documented

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/hyperdb#8]
I assume the `key` parameter is associated with the underlying `hypercore` but might be confusing to someone even more a new comer than me.

**Comment by mafintosh** [comment]
Ah yes. I just threw together the readme in a couple of mins. We should def clarify that

**Comment by noffle** [comment]
I think this is fixed by https://github.com/mafintosh/hyperdb/commit/63d924b03355d4ad13afb445234a11089f766572
