### ISSUE TITLE
Persistent hyperdb in browser

### ISSUE THREAD

**Issue by peacememories** [mafintosh/hyperdb#96]
I've been trying to get a persistent hyperdb to work in my browser for the past 2 days.
The problem is that hyperdb expects `random-access-storage` based storage as its backend, and the only existing implementation that works in the browser is `random-access-memory`, which is volatile. This would mean that everytime my browser tab is reloaded it will lose its content and when it connects to peers it will need to be reauthorized.

I've tried frankensteining together `level-browserify` and `random-access-memory`, but this is very error prone. Is there a backend for hyperdb that supports persistent browser storage? or maybe another way of preserving the key and replaying changes without breaking the database?

**Comment by caiogondim** [comment]
I myself never tried, but hope that helps https://github.com/substack/random-access-idb

**Comment by joehand** [comment]
> I myself never tried, but hope that helps https://github.com/substack/random-access-idb

:+1: this works with hyperdrive, should work with hyperdb as well.

**Comment by mafintosh** [comment]
What @joehand said :) Feel free to re-open if you're having issues

**Comment by eklem** [comment]
Did you ever get this to work, @peacememories ?

**Comment by peacememories** [comment]
I can’t quite remember (I never did finish that project) but I think I had success with random-access-idb

**Comment by joehand** [comment]
@eklem you can try random-access-web as well: https://github.com/random-access-storage/random-access-web

**Comment by eklem** [comment]
Thanks @joehand!
